/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_youjie_android_utils_JNITest */

#ifndef _Included_com_youjie_android_utils_JNITest
#define _Included_com_youjie_android_utils_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_youjie_android_utils_JNITest
 * Method:    getsecretKeyFromC
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_youjie_android_utils_JNITest_getsecretKeyFromC
  (JNIEnv *, jclass, jobject);


#ifdef __cplusplus
}
#endif
#endif
