//
// Created by qingchao on 2017/7/27.
//

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string.h>
#include <stdio.h>
/* Header for class com_youjie_android_utils_JNITest */

#ifndef _Included_com_youjie_android_utils_JNITest
#define _Included_com_youjie_android_utils_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_youjie_android_utils_JNITest
 * Method:    getbbCourseKeyFromC
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */

const char *AUTH_KEY = "y0uJay@pr1l";

const char *RELEASE_SIGN = "308202c1308201a9a00302010202045455d39c300d06092a864886f70d01010b05003011310f300d06035504031306796f756a6965301e170d3135303632303132343130385a170d3430303631333132343130385a3011310f300d06035504031306796f756a696530820122300d06092a864886f70d01010105000382010f003082010a028201010087dadf06b168df8bde16d318fb2ca15d82a2c1c3c03d2de0030551d9585286b80bf5d7348ec1bc0d7d72648eae8770a74aa95d9046e0ef29b0045f1ce3d25d3ae6320066707a028411c307f3ca6fb1ab2b242ee8be5bec369e55ae606e85af6b81b5fd421ac8eb1c936bd14f6fe7ccc2668b1746f9210cb57877aaee615491c84437233b0542efbe5335c358679de3c5781c1c7bc54152885b861728a48a54d1c1acee4ba41659e36d2fa6b5a7aa128c13dd3fe3684504c878c286afa3bfe261a1d48343da150e22f176af97cbae058ada88d2660a37d9827954bec8490506c57241bf1d3c9569d97bde0b42b10293f4fe635be743edcb2f39efef300835881d0203010001a321301f301d0603551d0e041604140fa00edf05b6a3144a96744a73720e50be39812c300d06092a864886f70d01010b050003820101002a1f62a337622225415fd6e5d6ef3b5e0be9103d608a3fd6d3c1e90f3c9b3b25991d5858d34cf812ae06bfc9e6a3685ad27e589aa914c8e711fa88a42a27bed7e30ee1d37d40f25619e0b6d1d7ef8dd030a2dd69c966157bd84151fae2a9b4927bac8ae9294dc512f9b7aa0859677510fcdbce17773dc6b4f4364ff82b12fee98ffbdb7a7294c13f74df6459cfdc9a170ad5c157deadaa43ebb4f24612df0397b3ad58827963d61ff88d820fde136802c565de0500afb2b93b930632e554a7d6ef60e4c207944e88e065f0b5286069396d7039292774f004339b0392fe1f6eb3bcb95b15a247d7dce72c92e842230cd2e3f681e8a66e5392fad6894b19d0f1c2";

JNIEXPORT jstring
JNICALL Java_com_youjie_android_utils_JNITest_getsecretKeyFromC
        (JNIEnv *env, jclass jclazz, jobject contextObject) {
    jclass native_class = env->GetObjectClass(contextObject);
    jmethodID pm_id = env->GetMethodID(native_class, "getPackageManager",
                                       "()Landroid/content/pm/PackageManager;");
    jobject pm_obj = env->CallObjectMethod(contextObject, pm_id);
    jclass pm_clazz = env->GetObjectClass(pm_obj);
    // 得到 getPackageInfo 方法的 ID
    jmethodID package_info_id = env->GetMethodID(pm_clazz, "getPackageInfo",
                                                 "(Ljava/lang/String;I)Landroid/content/pm/PackageInfo;");
    jclass native_classs = env->GetObjectClass(contextObject);
    jmethodID mId = env->GetMethodID(native_classs, "getPackageName", "()Ljava/lang/String;");
    jstring pkg_str = static_cast<jstring>(env->CallObjectMethod(contextObject, mId));
    // 获得应用包的信息
    jobject pi_obj = env->CallObjectMethod(pm_obj, package_info_id, pkg_str, 64);
    // 获得 PackageInfo 类
    jclass pi_clazz = env->GetObjectClass(pi_obj);
    // 获得签名数组属性的 ID
    jfieldID signatures_fieldId = env->GetFieldID(pi_clazz, "signatures",
                                                  "[Landroid/content/pm/Signature;");
    jobject signatures_obj = env->GetObjectField(pi_obj, signatures_fieldId);
    jobjectArray signaturesArray = (jobjectArray) signatures_obj;
    jsize size = env->GetArrayLength(signaturesArray);
    jobject signature_obj = env->GetObjectArrayElement(signaturesArray, 0);
    jclass signature_clazz = env->GetObjectClass(signature_obj);
    jmethodID string_id = env->GetMethodID(signature_clazz, "toCharsString",
                                           "()Ljava/lang/String;");
    jstring str = static_cast<jstring>(env->CallObjectMethod(signature_obj, string_id));
    char *c_msg = (char *) env->GetStringUTFChars(str, 0);
    //return str;
    if (strcmp(c_msg, RELEASE_SIGN) == 0)//签名一致  返回合法的 api key，否则返回错误
    {
        return (env)->NewStringUTF(AUTH_KEY);
    } else {
        return (env)->NewStringUTF("error");
    }
}
#ifdef __cplusplus
}
#endif
#endif
